name: Deploy Docker image to Minikube

on:
  push:
    branches:
      - test1
      - test2
      - main

env:
  DOCKER_REGISTRY: hub.docker.com/repository/docker
  DOCKER_REPOSITORY: owgrand/nexo_image
  DOCKER_USERNAME: owgrand
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  KUBECONFIG: ${{ env.GITHUB_WORKSPACE }}/kommander-cluster-admin-config

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker registry
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v4 
      with:
        context: .
        push: true
        tags: owgrand/nexo_image:latest
        #tags: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPOSITORY }}:latest #${{ env.GITHUB_SHA }}

    - name: Install Minikube
      run: |
        sudo apt-get update
        sudo apt-get install -y curl
        curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        chmod +x minikube
        sudo install minikube /usr/local/bin/

    - name: Start Minikube
      run: |
        minikube start --driver=none

    - name: Set kubectl context to Minikube
      run: |
        kubectl config use-context minikube

    - name: Deploy script to Minikube
      run: |
        kubectl --kubeconfig ${KUBECONFIG} get all --all-namespaces
