name: Push Docker image

on:
  push:
    branches:
      - main

env:
  DOCKER_REGISTRY: docker.pkg.github.com/OWGrand/Nexo_task
  DOCKER_USERNAME: OWGrand
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@latest

    - name: Checkout code
      uses: actions/checkout@latest

    - name: Build and push
      uses: docker/build-push-action@latest
      with:
        context: .
        push: true
        tags: ${{ env.DOCKER_REGISTRY }}/nexo_image:${{ env.GITHUB_SHA }}

    - name: Login to Docker registry
      uses: docker/login-action@latest
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}

    - name: Push Docker image
      uses: docker/push-action@latest
      with:
        tags: ${{ env.DOCKER_REGISTRY }}/nexo_image:${{ env.GITHUB_SHA }}

