name: Push Docker image

on:
  push:
    branches:
      - test1

env:
  DOCKER_REGISTRY: hub.docker.com/repository/docker/owgrand/ #github.com/OWGrand
  DOCKER_USERNAME: owgrand
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker registry
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v4 
      with:
        context: .
        push: true
        tags: ${{ env.DOCKER_REGISTRY }}/nexo_image:latest
        #tags: ${{ env.DOCKER_REGISTRY }}/Nexo_task:${{ env.GITHUB_SHA }}



#    - name: Push Docker image
 #     uses: docker/push-action@v3
  #    with:
   #     tags: ${{ env.DOCKER_REGISTRY }}/nexo_image:${{ env.GITHUB_SHA }}

