name: GetPods

on:
  push:
    branches:
      - test1
      - test2
      - test3
      - main 

jobs:
  example:
    name: Cluster interaction
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.7.2
        with:
          minikube version: 'v1.28.0'
          kubernetes version: 'v1.25.4'
          github token: ${{ secrets.DOCKER_PASSWORD }} 
      - name: Interact with the cluster
        run: kubectl --server=localhost:6666 get nodes
